### ISSUE TITLE
Loading screen when modifying files

### ISSUE THREAD

**Issue by daniferna** [Arquisoft/viade_es2b#106]
When creating, editing or adding a route the app doesn't show a loading screen and sometimes, depending on the complex of the route and the amount and weight of the multimedia files this time can be more than 10/15 seconds and the user can get to think that something is not working.
A loading screen could help with that.

**Comment by Ainiall** [comment]
A toaster could do the trick

**Comment by daniferna** [comment]
Closing, fixed with the new snackbars.
