### ISSUE TITLE
Problems in some web browsers

### ISSUE THREAD

**Issue by daniferna** [Arquisoft/viade_es2b#107]
We are aware that some web browser like Edge or Firefox may have problems loading translation and images files.

While we focus on Chrome, as stated in the documentation, we also would like to have the app running perfectly on every browser.

The error doesn't occur always and that make it more difficult for us to find the cause, also we are working in chrome most of the time so we detected it three days ago.

**Comment by daniferna** [comment]
Until we detect the error we strongly recommend the use of Google Chrome when using the app.

**Comment by Ainiall** [comment]
It works fine on Firefox and Opera too

**Comment by daniferna** [comment]
It seems to be fixed. We suspect it was a problem with the router which is now fixed, closing the issue.
