### ISSUE TITLE
Archivo ejemplo ruta

### ISSUE THREAD

**Issue by HugoLebredo** [Arquisoft/viade_es2b#25]
Os paso un ejemplo de archivos gpx. 
Ese repositorio tiene más ejemplos.

[Ruta ejemplo](https://github.com/gps-touring/sample-gpx/blob/master/BrittanyJura/Campsites/filtered-brittany-jura-archies_fr.gpx)

**Comment by uo265349** [comment]
Pretty helpful in order to test how the routes show in the map and fix different problems so that it works fine, now closing issue
