### ISSUE TITLE
Solution for the routes with the same name.

### ISSUE THREAD

**Issue by daniferna** [Arquisoft/viade_es2b#30]
Right now when we have two routes with the same name there is no way to distinguish them in the list of route. We should find a solution for that issue in the future.

We should define a standard way to define the id, maybe involving the computer time or something like these.

Right now this two issues are considered as a technical debt sue to the proximity of the delivery of the first prototype.

**Comment by UO251683** [comment]
I recommend use use the next code:
<name>#<Id>
to distinguish each one to another with the same name, being use this like a key value and show it in the list of routes.

**Comment by daniferna** [comment]
Solved.
I save the route with the following code:
name-Date.now().toString()
