### ISSUE TITLE
Interface viade_es2b

### ISSUE THREAD

**Issue by Ainiall** [Arquisoft/viade_es2b#36]
The display of the web is shown incorrectly. It doesn't load in the same way as it does locally.

**Comment by Ainiall** [comment]
I've changed every option I could find and it's not working still. I've even tried to deploy it manually using npm run deploy. Somehow it ignores /viade_es2b.

https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string

**Comment by daniferna** [comment]
I fixed some things.
As I see it now we have to solve two things:

- The typography is weird, it uses ComicSans ¿?
- The bottom bar is not at the bottom.

I will keep working on these issues.

**Comment by daniferna** [comment]
I fixed it. Closing the issue.
