### ISSUE TITLE
Edit route problems

### ISSUE THREAD

**Issue by daniferna** [Arquisoft/viade_es2b#80]
I detected some problems on the edit route:

- If the new route page is already open, when clicking the pencil icon, the edit route form doesn't show up.
- If the name of the route has spaces, the route doesn't modify.
- The route info before editing it should be showed in the form.
- It shouldn't be needed to click the route name before the pencil icon to edit the route.

**Comment by UO251683** [comment]
Already fixed:
* If the name of the route has spaces, the route doesn't modify.
* The route info before editing it should be showed in the form.

Working on:
* It shouldn't be needed to click the route name before the pencil icon to edit the route.
* If the new route page is already open, when clicking the pencil icon, the edit route form doesn't show up.

**Comment by daniferna** [comment]
Found new issues, the edit form and the downloading gpx for the public routes is not working, which is reasonable because we didn't support them before.

**Comment by daniferna** [comment]
> Found new issues, the edit form and the downloading gpx for the public routes is not working, which is reasonable because we didn't support them before.

Also, keep in mind we will list also the routes shared with the users in a near future, stored at /shared/routes.

**Comment by UO251683** [comment]
I will work to support this 2 new kind of routes in both functionalities.
